### ISSUE TITLE
create session error

### ISSUE THREAD

**Issue by bgobi1991** [opentok/opentok-node#106]
Hi ,
when i run this application through this error,

Error: Failed to createSession. Error: An authentication error occurred: (403) <
?xml version="1.0" encoding="UTF-8" standalone="yes"?><errorPayload><code>-1</co
de><message>Invalid partner credentials</message></errorPayload>
    at D:\Projects\Examples\opentok-node-master\lib\opentok.js:378:30
    at Request._callback (D:\Projects\Examples\opentok-node-master\lib\client.js
:48:14)

**Comment by aoberoi** [comment]
@bgobi1991 this means that the API Key and Secret you provided were incorrect. Please double-check. If you think you have the correct values and are still getting these errors, please email support@tokbox.com
