### ISSUE TITLE
Pass additional data in archive errors

### ISSUE THREAD

**Issue by mmiszy** [opentok/opentok-node#110]
Currently when `startArchive` function fails, only a very generic error message is returned to the application instead of the whole response from the API.
There's no way to differentiate between actual errors and notifications (eg. "This session is already being archived.") – both will be visible as "Unexpected response from OpenTok".

**Comment by aoberoi** [comment]
thanks @mmiszy, i agree that more specific data about the error would be helpful. specifically, i'd like to define more granular error types so they can be dealt with individually. i've linked to a ticket where i'd like to collect thoughts about error standardization. this will also impact opentok server SDKs in other languages as well.

typically if you are getting "the session is already being archived", this is a logical error in your code, as you should already know if you started an archive on a session or not. this should only happen in development. in this case, i don't believe defining an error type is critical to building an application. seeing as such i'm closing this issue in favor of the discussion moving to the other ticket.
