### ISSUE TITLE
looks like a lodash version update is probably a good idea

### ISSUE THREAD

**Issue by victusfate** [opentok/opentok-node#113]
npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.

also applies to opentok-token. Looks like quite a few dependencies all rely on it as well: findup-sync, grunt-legacy-log-utils@0.1.1, grunt-legacy-util@0.2., nock@0.42.3. Maybe update a few of these as well?

**Comment by aoberoi** [comment]
agreed! thanks for the heads up.

**Comment by jdalton** [comment]
:clap:

**Comment by davidglbr** [comment]
+1

**Comment by aoberoi** [comment]
fixed by #133
