### ISSUE TITLE
Stop obfuscating errors.

### ISSUE THREAD

**Issue by davidj-lynxlogic** [opentok/opentok-node#114]
The node SDK has code in it that obfuscates errors coming back from the REST API. For example, there's this code in the startArchive method:

```
if(err) {
      callback(err);
    } else if(response.statusCode != 200) {
      if(response && response.statusCode == 404) {
        callback(new errors.ArchiveError('Session not found'));
      } else if(response && response.statusCode == 403) {
        callback(new errors.AuthError('Invalid API key or secret'));
      } else {
        console.log ('Unexpected response from OpenTok: %j', response); // davidj
        callback(new errors.RequestError('Unexpected response from OpenTok'));
      }
    } else if(body.status != 'started') {
      callback(new errors.RequestError('Unexpected response from OpenTok'));
    } else {
      callback(null, new Archive(config, body));
    }
```
Any error that isn't a 404 or 403 is hidden, and instead a generic 'Unexpected response from OpenTok' message is returned.  I've had to hack into the code to troubleshoot problems and find out the real cause of errors. Here's an example of data that came back in the response that would have been really useful to provide in the error object:

"statusCode":400,
"body":{"message":"Not found. No clients are actively connected to the OpenTok session."...

**Comment by aoberoi** [comment]
@davidj-lynxlogic i totally agree with your concern. i'm going to link this issue to the overall error handling issue that already exists (#60), and then close it.
