### ISSUE TITLE
Adopt ESLint with AirBnB's ES5 compatible configuration

### ISSUE THREAD

**Issue by aoberoi** [opentok/opentok-node#130]
Use: eslint-config-airbnb-base/legacy from https://www.npmjs.com/package/eslint-config-airbnb-base

**Comment by hbaqai** [comment]
Though we don't have any checks to prevent commits that do not adhere to linting guidelines, we have started to lint the repository.

**Comment by MichaelJolley** [comment]
This was completed some time ago, but the issue was not closed.
