### ISSUE TITLE
Add support for Moderation API

### ISSUE THREAD

**Issue by ggarber** [opentok/opentok-node#136]
This is a request for comments regarding the API for upcoming platform functionality. The platform functionality is not generally available at the moment and there is no guarantee it will be released in any form.
### Disconnect a participant

You can disconnect participants from an OpenTok Session using the
`opentok.forceDisconnect(sessionId, connectionId, callback)` method.

``` javascript
opentok.forceDisconnect(sessionId, connectionId, function(error) {
  if (error) return console.log("error:", error);
});
```

**Comment by aiham** [comment]
Merged in #160

**Comment by mcblum** [comment]
@ggarber question for you - how do I actually know the connection ID server-side?

**Comment by msach22** [comment]
@mcblum You can use session monitoring to set up webhook events. As of now, session monitoring delivers the following 4 events:
- connectionCreated
- connectionDestroyed
- streamCreated
- streamDestroyed

The connection events have the `connectionId` property that you're looking for.

**Comment by mcblum** [comment]
@msach22 awesome, thank you!
