### ISSUE TITLE
getting error

### ISSUE THREAD

**Issue by rajanishtimes** [opentok/opentok-node#165]
When Installing 

npm install opentok --save

getting below error please help

npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "opentok" under a package
npm ERR! also called "opentok". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR! 
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-09-10T18_53_57_974Z-debug.log

**Comment by aiham** [comment]
@rajanishtimes You need to rename your folder from `opentok` to something else otherwise npm will not let you install the `opentok` package.
