### ISSUE TITLE
Error: Cannot find module 'lodash'

### ISSUE THREAD

**Issue by songproducer** [opentok/opentok-node#172]
Hi, just trying to get started.

When i go
node index.js

I get:

module.js:540
    throw err;
    ^

> 
> Error: Cannot find module 'lodash'
>     at Function.Module._resolveFilename (module.js:538:15)
>     at Function.Module._load (module.js:468:25)
>     at Module.require (module.js:587:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (/Users/leotreasure/opentok-node/lib/opentok.js:7:9)
>     at Module._compile (module.js:643:30)
>     at Object.Module._extensions..js (module.js:654:10)
>     at Module.load (module.js:556:32)
>     at tryModuleLoad (module.js:499:12)
>     at Function.Module._load (module.js:491:3)
>

**Comment by msach22** [comment]
@songproducer Hmm, did you run `npm install` in the main folder? The individual samples such as Archiving and Hello World are using the libraries from the `lib` folder which have a `lodash` dependency.

**Comment by songproducer** [comment]
Aha! Thanks I had run it in the Archiving folder
