### ISSUE TITLE
generateJwt Fails thinking it is issued in the future

### ISSUE THREAD

**Issue by kevineaton** [opentok/opentok-node#177]
I am using opentok 2.6.2. When doing local development (we are physically located in the Eastern Timezone in the US) we can create a session without any issues. However, when we dockerized our app and pushed it to our servers (set to UTC), we started getting the following error:

`Error: Failed to createSession. Error: An authentication error occurred: (403) {"code":-1,"message":"issued time cannot be greater than current time","description":"issued time cannot be greater than current time"}`

I was confused, as we were sending in anything date related to the createSession call. I tracked it down to generateJwt.js. When I had my docker image replace the file with this:
```
var jwt = require('jsonwebtoken');

module.exports = function (config) {
  // var currentTime = Math.floor(new Date() / 1000);
  var currentTime = Math.floor(new Date() / 1000) - (60 * 60 * 1);
  var expires = currentTime + (60 * 60 * 6);
  var token = jwt.sign({
    iss: config.apiKey,
    ist: 'project',
    iat: currentTime,
    exp: expires
  }, config.apiSecret);

  return token;
};
```
I was able to get the session to create. I am not sure if the problem is on the client side or on the server. Maybe related to the timezones, or maybe there is a some latency that is occurring that is confusing the server.

We have the workaround in place to manually copy this file in after the `npm install` in the Dockerfile. However, that is obviously not ideal. I could open a PR, but I am not familiar enough with the RESTful service to know if it is better handled by them.

I am open to other ideas if this is a symptom and not the root cause. But it did seem to fix our problem.

**Comment by sharathm** [comment]
Same problem. 
Works fine locally but once deployed to a server, this occurs.
The change above is working for me as well..

`timedatectl` gives..

```
      Local time: Tue 2018-06-19 06:59:32 UTC
  Universal time: Tue 2018-06-19 06:59:32 UTC
        RTC time: Tue 2018-06-19 06:58:00
       Time zone: Etc/UTC (UTC, +0000)
 Network time on: yes
NTP synchronized: yes
 RTC in local TZ: no
```

**Comment by justacoder** [comment]
This solution caused the time to then be 'behind' the TokBox server. 

Solving that problem, [here](https://github.com/opentok/OpenTok-PHP-SDK/issues/202#issuecomment-378247757): like this:

> sudo ntpdate time.nist.gov

worked for me, setting my linux server's time to the true time.
