### ISSUE TITLE
Record more than one archive at a time

### ISSUE THREAD

**Issue by yusuftor** [opentok/opentok-node#185]
I need to record multiple archives at a time and am wondering if this could be possible in the future? What I'd like to do is record the whole stream, but every now and then also record smaller clips of the stream at the same time.

**Comment by msach22** [comment]
@yusuftor You can only make one archive of a session at a time. Unfortunately that is not a feature that this SDK can support until the API supports it itself. To file for a feature request, please email support@tokbox.com 😄
