### ISSUE TITLE
Error CORS policy when call api Start Archive

### ISSUE THREAD

**Issue by taiphamhdweb** [opentok/opentok-node#196]
I call API start-archive. I have an error as bellow, please check help me.
Access to fetch at 'https://api.opentok.com/v2/project/<archive_id_value>/archive' from origin 'my-domain.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by msach22** [comment]
@taiphamhdweb Thanks for filing an issue, it looks like you're making the `startArchive` call from our server? 
Could you please check out this answer to see if it solves your issue?
https://stackoverflow.com/questions/50889376/opentok-rest-api-doesnt-work/50913192#50913192

**Comment by taiphamhdweb** [comment]
Thanks you @msach22, This issue is solved.
