### ISSUE TITLE
opentok screen sharing for edge with getDisplayMedia

### ISSUE THREAD

**Issue by perzequiel** [opentok/opentok-node#202]
Hi,

I am using the @opentok/client for implement a video session with screen sharing option in a react web application, I could make it works for chrome and firefox and i saw in the documentation that the current version of the library not support screen sharing for edge, 
more details [https://tokbox.com/developer/beta/edge/](url).

But i found a way to make the screen sharing works in edge using getDisplayMedia (show the screen in a html tag)
[https://github.com/muaz-khan/WebRTC-Experiment/tree/master/getDisplayMedia](url)
however, the screen sharing is working and create a stream but i can't push that stream into the opentok session, this is a bit example:

[https://codepen.io/perzequiel/pen/ZwwJWq?editors=1000#0](url)
uncomment apiKey, sessionId and token and I am using from here [https://tokbox.com/developer/quickstart/](url)

In case to be posible it could be a workaround for edge (experimental), I really need to get screen sharing feature on edge.

Thanks.

**Comment by MichaelJolley** [comment]
Sharing your screen with the latest version of the OpenTok client should work in Edge now.

Thanks @perzequiel
