### ISSUE TITLE
Address outdated type definitions

### ISSUE THREAD

**Issue by rossng** [opentok/opentok-node#231]
The unofficial type definitions provided through DefinitelyTyped (`@types/opentok`) have become pretty outdated and are missing a bunch of methods in the current version (2.10.0) of the SDK.

Given how widespread TypeScript usage is today, it would make sense to either support these officially or bring them into the repository itself.

As a stop-gap measure, I've made my own PR to DefinitelyTyped that should bring the definitions fairly up to date.

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49959

**Comment by kellyjandrews** [comment]
Thanks for this @rossng - I'm hoping we can get better TypeScript support starting next year.  Appreciate your contribution to the community with this.

**Comment by manchuck** [comment]
Closing as we are not doing any enhancements on this SDK. Please consider migrating to the [Vonage Video platform](https://developer.vonage.com/en/video/overview)
