### ISSUE TITLE
latest version 2.18.4

### ISSUE THREAD

**Issue by diego26lights** [opentok/opentok-node#234]
It looks like the [latest version of opentok](https://static.opentok.com/v2/js/opentok.min.js) is 2.18.4 which seems to support iOS/Safari since 2.16 (and we need iOS/Safari support on our web app :)).
The current project version is 2.10.0.

How can we update our node app to the latest opentok js ?

**Comment by kellyjandrews** [comment]
You should be able to run `npm install --save @opentok/client@latest` to update the package.
