### ISSUE TITLE
Grant the ability to subscribe to session events on the server side

### ISSUE THREAD

**Issue by RoeelCohen** [opentok/opentok-node#238]
As the business owner I would want to know when a user is disconnected from a session and for how long.
i.e. count the "alive" time of that session.

Currently I can't see the option to listen to session events or number of participants in a session from the backend code
Am I missing something?

I did think of few workarounds but I'm not sure they would be considered as a good practice.
1. Use the web client module to connect as another subscriber to every session.
2. Sending a "user disconnected" event from the other user in the call (seems as a bad bad idea).

or can we please grant the ability to subscribe to session events on the server side?

**Comment by kellyjandrews** [comment]
I think you are looking for Session Monitoring - https://tokbox.com/developer/guides/session-monitoring/
