### ISSUE TITLE
Error: The token does not match the session ID. reporting randomly

### ISSUE THREAD

**Issue by gopaljoshi-brainvire** [opentok/opentok-node#240]
I have been using opentok for 3 years. Sometimes it gives an error of `Error: The token does not match the session ID.`. I am aware that if the wrong security token is passed then opentok gives this error. My problem is my token is correct and its giving error randomly. In April'21 i saw this error 4 times randomly.

Sometimes it gives an error in the middle of the call I am not able to figure out how can it stops working in between of video call. Did anyone face the same issue?

**Comment by manchuck** [comment]
@gopaljoshi-brainvire sounds like you might have mucked up the session ID and token. Closing this issue as stale.  If you are still having an issues, then please open a new ticket
