### ISSUE TITLE
streamMode is missing in archive options

### ISSUE THREAD

**Issue by woodja** [opentok/opentok-node#266]
https://github.com/opentok/opentok-node/blob/51f7b339f78413952904edf0e011a3d0a25c1785/lib/archiving.js#L269
JSON options needs
`streamMode: options.streamMode`

**Comment by moficodes** [comment]
@woodja Thanks for creating the issue.

**Comment by moficodes** [comment]
[opentok server sdk@2.14.1](https://www.npmjs.com/package/opentok) released
