### ISSUE TITLE
2.17.0 breaks due to SyntaxError, automatic json parsing in needle

### ISSUE THREAD

**Issue by borkanee** [opentok/opentok-node#316]
2.17.0 breaks when using listStreams and probably listBroadcasts and stopBroadcast as well,, we have gone back to 2.16.0 in the meantime.

It seems to be related to the switch from request to needle as needle automatically parses json unless _options.parse_ is set to _false_ and as far is I can see it is not set at the moment in version 2.17.0, which leads to JSON.parse() throwing errors. You could either set _parse:false_ on the specific request or simply change the defaults for all request by setting _parse_response: false_: on the defaults. Read more here: https://github.com/tomas/needle/#overriding-defaults

Another option could be to simply remove the JSON.parse() in the requestCallbacks.

**Comment by tapz** [comment]
I created a ticket to Vonage about this.

**Comment by manchuck** [comment]
This has been resolved
