### ISSUE TITLE
Session not found error when manual archive startArchive right after createSession with valid session id.

### ISSUE THREAD

**Issue by samuveljohns** [opentok/opentok-node#317]
**Issue**:
We are able to create a opentok session with createSession() and get the sessionId.
const archiveOptions = {
      name: "Example",
      hasAudio: true,
      hasVideo: false,
      outputMode: "individual",
    };
Next line we call opentok.startArchive(sessionId, archiveOptions) but this is returning Session not found error.

but when we write opentok.startArchive in a seperate api. which is working as expected. Archive is started.

**Comment by manchuck** [comment]
@samuveljohns can you please provide more code examples? I am unable to reproduce
