### ISSUE TITLE
Standardize error handling

### ISSUE THREAD

**Issue by aoberoi** [opentok/opentok-node#60]
There needs to be a set of Error types defined and their meaning nailed down so that developers can predictably deal with error conditions.

This will also be subject to an internal API Review.

**Comment by aoberoi** [comment]
A specific use case where error types are preferable is in #110

**Comment by aoberoi** [comment]
In #114, the case is made that we should propagate error messages that come from the REST API rather than squelching them and covering them up with a generic message.

The way forward from this point is with an actual API proposal.

**Comment by MichaelJolley** [comment]
Closing as outdated.
