### ISSUE TITLE
refactor tests to use nock back fixtures

### ISSUE THREAD

**Issue by aoberoi** [opentok/opentok-node#83]
nock, the http intercepting module used, has a new feature called nock back (https://github.com/pgte/nock#nock-back). it can be used to get the fixtures of requests/replies out of the test code and into a declarative json file. this would make things much cleaner.

**Comment by aoberoi** [comment]
it would be lovely to include some documentation in `DEVELOPING.md` about usage of the recorder, the workflow, and the modes.

**Comment by MichaelJolley** [comment]
Closing as outdated.
