### ISSUE TITLE
refactor archiving implementation to be more seamless

### ISSUE THREAD

**Issue by aoberoi** [opentok/opentok-node#84]
the current archiving implementation is built as a functional "extension" of the OpenTok object definition. it would be nice to clean this up to make the code less repetitive and harmonious. this also includes the jasmine based tests (which contrast with the other mocha based tests).

it would be favorable to keep the implementation of archiving decoupled. one possible solution is to export a "mix-in" function from `lib/archiving.js` that could be used to extend `OpenTok.prototype`.

**Comment by MichaelJolley** [comment]
Closing as outdated.
